language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli-ghpages

script:
  - ng test
  - ng e2e
  - ng build --prod --base-href "https://Qi-Z.github.io/d3-gallery/"

after_success:
  - ngh --repo="https://GH_TOKEN@b1812d944c23b5010c1f5033b73572ac7d093bf5@github.com/Qi-Z/d3-gallery.git"
