language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --base-href "https://Qi-Z.github.io/d3-gallery/"

after_success:
  - ngh
